# Use the official OpenJDK base image
FROM openjdk:11

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container
COPY StockMarketApp.jar /app/StockMarketApp.jar

# Expose the port that the application will run on
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "StockMarketApp.jar"]
